package PACKAGE.dto;

import PACKAGE.entities.OBJNAME_CAPITALCAMELCASE;
import PACKAGE.entities.User;

public class OBJNAME_CAPITALCAMELCASE()DTO {

	public OBJNAME_CAPITALCAMELCASE OBJNAME_LOWERCAMELCASE;
	public User user;

}
